CREATE DATABASE IF NOT EXISTS fundoo_users;
CREATE DATABASE IF NOT EXISTS fundoo_notes;
CREATE DATABASE IF NOT EXISTS fundoo_labels;
CREATE DATABASE IF NOT EXISTS fundoo_notifications;
CREATE DATABASE IF NOT EXISTS fundoo_reminders;
